project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lab1.qmd
        text: Laboratorios
      - href: eda.qmd
        text: Eda
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
