project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: MidTerm
        href: midterm.qmd
      - text: Proyecto Final
        href: Pfinal.qmd
      - section: "Laboratorios"
        contents:
          - lab1.qmd
          - lab2.qmd
      - text: Eda
        href: eda.qmd
        
      
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
